### ISSUE TITLE
问题： Index is supposed to be a vector

### ISSUE THREAD

**Issue by Yusifu** [hedwigi/transformer-notes#1]
你好呀~

我最近也在学习transformer和pytorch，正在阅读哈佛的教程，非常感谢你整理的代码，十分明了，对于学习很有帮助。
但是在运行代码的时候，出现Index is supposed to be a vector这样的问题，请问你遇到过吗？
再你的环境中可以跑通吗？

谢谢~
```
Traceback (most recent call last):
  File "/home/zhangmy/srl/transformer/pytorch03forharvard/main.py", line 137, in <module>
    SimpleLossCompute(model.output_layer, criterion, model_opt))
  File "/home/zhangmy/srl/transformer/pytorch03forharvard/main.py", line 69, in run_epoch
    loss = loss_compute(out, batch.trg_y, batch.ntokens)
  File "/home/zhangmy/srl/transformer/pytorch03forharvard/train_helper/SimpleLossCompute.py", line 12, in __call__
    y.contiguous().view(-1)) / norm
  File "/home/zhangmy/.conda/envs/basecopy/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhangmy/srl/transformer/pytorch03forharvard/model/regularization/LabelSmoothing.py", line 26, in forward
    true_dist.index_fill_(0, mask.squeeze(), 0.0)
RuntimeError: invalid argument 3: Index is supposed to be a vector at /pytorch/aten/src/TH/generic/THTensorMath.c:553
```

**Comment by Yusifu** [comment]
谢谢！跑通了，是pytorch的版本问题，改成了0.3版本就可以了，之前是0.4版本
